// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("atlassian_sampling")
	ScopeName = "bitbucket.org/atlassian/observability-sidecar/pkg/processor/atlassiansamplingprocessor"
)

const (
	TracesStability = component.StabilityLevelAlpha
)
